services:
  # FastAPI Backend
  portfolio_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio_backend
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/app  # Remove in final prod to use code inside image
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
      - ./.env
    depends_on:
      portfolio_db:
        condition: service_healthy
    command: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

  # Vite Frontend
  portfolio_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio_frontend
    ports:
      - "80:80"
    depends_on:
      - portfolio_backend
    restart: always

  # PostgreSQL with pgvector for RAG
  portfolio_db:
    image: pgvector/pgvector:0.8.1-pg17
    container_name: portfolio_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
